#!/usr/bin/env node
/**
 * Build module/portrait-manifest.json from the shipped character art.
 *
 *   node tools/import/portraits.mjs [--dry]
 *
 * Two sibling folders hold the art, one image per character with matching
 * filenames in each:
 *
 *   character_portraits/<name>.webp   shown on the actor sheet (actor.img)
 *   character_tokens/<name>.webp      prepped token art (prototypeToken texture)
 *
 * The manifest is a plain list of the paired basenames. It exists because the
 * client cannot enumerate a server folder without the FILES_BROWSE permission,
 * and character generation runs player-side; shipping the list as data means
 * generation and the portrait gallery never need to browse the filesystem.
 *
 * Art: CC BY 4.0, artist Jon Aspeheim (see the license.txt in each folder).
 *
 * Re-runnable and byte-stable: the output is the sorted list of every portrait
 * that has a matching token, so adding art later is just a rerun. Any portrait
 * without a token (or token without a portrait) is reported and left out.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const PORTRAITS = path.join(root, "art", "jon-aspeheim", "portraits");
const TOKENS = path.join(root, "art", "jon-aspeheim", "tokens");
const OUT = path.join(root, "module", "portrait-manifest.json");
const dry = process.argv.includes("--dry");

const webps = dir =>
  new Set(fs.readdirSync(dir).filter(f => f.toLowerCase().endsWith(".webp")));

const portraits = webps(PORTRAITS);
const tokens = webps(TOKENS);

const paired = [...portraits].filter(f => tokens.has(f)).sort();
const orphanPortraits = [...portraits].filter(f => !tokens.has(f)).sort();
const orphanTokens = [...tokens].filter(f => !portraits.has(f)).sort();

if (orphanPortraits.length)
  console.warn(`WARN  ${orphanPortraits.length} portrait(s) with no matching token (excluded): ${orphanPortraits.join(", ")}`);
if (orphanTokens.length)
  console.warn(`WARN  ${orphanTokens.length} token(s) with no matching portrait (excluded): ${orphanTokens.join(", ")}`);

const manifest = {
  _comment: "Generated by tools/import/portraits.mjs. Art: CC BY 4.0, artist Jon Aspeheim.",
  portraitDir: "systems/mondolme/art/jon-aspeheim/portraits",
  tokenDir: "systems/mondolme/art/jon-aspeheim/tokens",
  names: paired,
};

const json = JSON.stringify(manifest, null, 2) + "\n";

console.log(`${paired.length} paired portrait/token images`);
if (dry) {
  console.log("(dry run, not writing)");
} else {
  fs.writeFileSync(OUT, json);
  console.log(`wrote ${path.relative(root, OUT)}`);
}
